language: go

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go version

install:
  - go get -v

script: go build -v

after_success:
  -
notifications:
  email:
    on_success: change
    on_failure: always 
